export default {
  arrowright1: require('../assets/Images/arrow_right1.png'),
  Demo: require('../assets/Images/Demo.png'),
  eye: require('../assets/Images/eye.png'),
  eyeclose: require('../assets/Images/eye_close.png'),
  email: require('../assets/Images/email.png'),
  Password: require('../assets/Images/Password.png'),
  home: require('../assets/Images/home.png'),
  home_h: require('../assets/Images/home_h.png'),
  user: require('../assets/Images/user.png'),
  user_h: require('../assets/Images/my_profile_h.png'),
  heart: require('../assets/Images/heart.png'),
  heartfill: require('../assets/Images/heartfill.png'),
  logout: require('../assets/Images/logout.png'),
};
